apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: mongodb
  name: mongodb
spec:
  selector:
    matchLabels:
      service: mongodb
  template:
    metadata:
      labels:
        service: mongodb
    spec:
      containers:
      - image: nexus.informatik.haw-hamburg.de/mongodb
        name: mongodb
        ports:
        - containerPort: 27017
          protocol: TCP
        volumeMounts:
        - name: mongodb-vol
          mountPath: /data/db
      volumes:
      - name: mongodb-vol
        persistentVolumeClaim:
          claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: mongodb
  name: mongodb
spec:
  ports:
  - name: db 
    port: 27017
    targetPort: 27017
  selector:
    service: mongodb
  type: ClusterIP

