apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  labels:
    service: mongodb
spec:
  accessModes:
    - ReadWriteOnce # just one node can access
  resources:
    requests:
      storage: 5Gi
