# makefile
#

# # KONSTANTS


# # COMPI
CC = /usr/bin/gcc

CFLAGS += -D_REENTRANT
CFLAGS += -ggdb
CFLAGS += -Wall
CFLAGS += -ansi

LDFLAGS = -lpthread

what:
	echo $(CC)
	echo $(CFLAGS)
	echo $(LDFLAGS)
