apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pv-claim
  namespace: cies # without namespace -> namespace of projectscope
  labels:
    service: cies-svc
spec:
  accessModes:
    - ReadWriteOnce # just one node can access
  resources:
    requests:
      storage: 5Gi
